#! /bin/bash 

if [[ -z $1 ]] ;then
	echo "This script need at least one valid distro version passed as param"
	echo ""
	echo "Usage example:"
	echo "$0 [0.0.1] [0.1.2] ... [x.x.x] "
	exit;
fi

function validate() {
for VALID_DISTRO_VERSION in "$@";
do
	if [[ $DETECTED_DISTRO_VERSION == $VALID_DISTRO_VERSION ]]; then
		DETECTED_VALID_DISTRO_VERSION=$DETECTED_DISTRO_VERSION;
		break
	fi 
done


if [[ -z $DETECTED_VALID_DISTRO_VERSION  ]]
then
	echo ""
      echo "Unable to determinate your Distro version or the given one \"$DETECTED_DISTRO_VERSION\" is not among the valid distro names." 
      echo "Valid distro versions are:"
      for name in "$@"; do echo "$name"; done
      echo ""
      read -p "Please type one of the versions from the above list to select it: " DETECTED_DISTRO_VERSION
      validate $@

else
	echo ""
      echo "$DETECTED_VALID_DISTRO_VERSION has been selected as your installation distro version"
fi

}

#DETECTED_DISTRO_VERSION=$(lsb_release -c | cut -f 2)
validate $@
export DETECTED_VALID_DISTRO_VERSION




